//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strings.Loc", typeof(Loc).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author: Chan Aleksey.
        /// </summary>
        public static string AboutPage_AuthorLabel {
            get {
                return ResourceManager.GetString("AboutPage_AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About....
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://aleksey.chan.github.io/mdOrganizer.
        /// </summary>
        public static string AppSite {
            get {
                return ResourceManager.GetString("AppSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mdOrganizer.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New note.
        /// </summary>
        public static string EditorPage_AddTitle {
            get {
                return ResourceManager.GetString("EditorPage_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit note.
        /// </summary>
        public static string EditorPage_EditTitle {
            get {
                return ResourceManager.GetString("EditorPage_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parent category.
        /// </summary>
        public static string EditorPage_ParentCategory {
            get {
                return ResourceManager.GetString("EditorPage_ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string EditorPage_SaveBtn {
            get {
                return ResourceManager.GetString("EditorPage_SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter note or category caption.
        /// </summary>
        public static string EditorPage_TitleLabel {
            get {
                return ResourceManager.GetString("EditorPage_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clone file.
        /// </summary>
        public static string Menu_CloneFile {
            get {
                return ResourceManager.GetString("Menu_CloneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New file.
        /// </summary>
        public static string Menu_NewFile {
            get {
                return ResourceManager.GetString("Menu_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        public static string Menu_OpenFile {
            get {
                return ResourceManager.GetString("Menu_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Root.
        /// </summary>
        public static string NotesIndex {
            get {
                return ResourceManager.GetString("NotesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string SettingsPage_ChooseLanguage {
            get {
                return ResourceManager.GetString("SettingsPage_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you use the &quot;Share...&quot; function from another application, you must first go to the desired category, and then tap on &quot;Add&quot;.
        /// </summary>
        public static string SettingsPage_ManualCategoryLabel {
            get {
                return ResourceManager.GetString("SettingsPage_ManualCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart required.
        /// </summary>
        public static string SettingsPage_RestartSettings {
            get {
                return ResourceManager.GetString("SettingsPage_RestartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsorted.
        /// </summary>
        public static string UnsortedCategory {
            get {
                return ResourceManager.GetString("UnsortedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add note.
        /// </summary>
        public static string ViewerPage_Add {
            get {
                return ResourceManager.GetString("ViewerPage_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose category.
        /// </summary>
        public static string ViewerPage_ChooseCategoryTitle {
            get {
                return ResourceManager.GetString("ViewerPage_ChooseCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This will clear all content!
        ///Continue?.
        /// </summary>
        public static string ViewerPage_ClearConfirm {
            get {
                return ResourceManager.GetString("ViewerPage_ClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all notes.
        /// </summary>
        public static string ViewerPage_ClearTitle {
            get {
                return ResourceManager.GetString("ViewerPage_ClearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This will delete &apos;{0}&apos;!
        ///Continue?.
        /// </summary>
        public static string ViewerPage_DeleteConfirm {
            get {
                return ResourceManager.GetString("ViewerPage_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete note.
        /// </summary>
        public static string ViewerPage_DeleteTitle {
            get {
                return ResourceManager.GetString("ViewerPage_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string ViewerPage_No {
            get {
                return ResourceManager.GetString("ViewerPage_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload.
        /// </summary>
        public static string ViewerPage_Refresh {
            get {
                return ResourceManager.GetString("ViewerPage_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mark notes containing text.
        /// </summary>
        public static string ViewerPage_SearchBar {
            get {
                return ResourceManager.GetString("ViewerPage_SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change view mode.
        /// </summary>
        public static string ViewerPage_ViewMode {
            get {
                return ResourceManager.GetString("ViewerPage_ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string ViewerPage_Yes {
            get {
                return ResourceManager.GetString("ViewerPage_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase font size.
        /// </summary>
        public static string ViewerPage_ZoomIn {
            get {
                return ResourceManager.GetString("ViewerPage_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease font size.
        /// </summary>
        public static string ViewerPage_ZoomOut {
            get {
                return ResourceManager.GetString("ViewerPage_ZoomOut", resourceCulture);
            }
        }
    }
}
